### PR TITLE
Allow customizing default baud rate at compile time, add USB options to Makefile.cfg

### PR DESCRIPTION
**Pull request by darcagn**
This PR allows setting the default baud rate in the Makefile.cfg. It renames the ambiguous `SERIALSPEED` value to `INITIAL_SPEED` and adds the `DESIRED_SPEED` value to allow users to set the default negotiated speed after initial serial connection while maintaining compatibility with existing dcload-serial discs.

Additionally it adds commented defaults for USB device and speed to help guide users who might be new to setting up dctool in a modern environment. 

Creating PR as draft as I haven't actually been able to test this yet.

### CODE REVIEW

**Comment by ljsebald** [comment]
I still do not understand why this is necessary.

As long as both dcload and dc-tool are both compiled with the same speed, there's not any problems changing that in the Makefile without this PR. This does the same thing as what happens now, other than adding an extra step of setting the initial speed, then changing to the desired speed.

Think about it this way: How does the behavior differ between setting INITIAL_SPEED to 115200 with this PR versus setting SERIALSPEED to the same without it? It doesn't have any effective difference.

**Comment by ljsebald** [comment]
After talking things over on Discord a bit, I suggest this PR be modified as follows:
1. Create a constant both in dcload and dc-tool of an initial serial speed (set it to 57600 for maximum compatibility). There is zero reason to allow users to change this value and it only leads to confusion. This can be called `INITIAL_SPEED` like it is in this PR, but it should not be changeable in the Makefile.cfg.
2. Rename the `SERIALSPEED` option from the Makefile.cfg to `TOOL_DEFAULT_SPEED` (or something like that). Document that it only affects the dc-tool side (and the rest of the documentation for `DESIRED_SPEED` looks reasonable).
3. Use the new `TOOL_DEFAULT_SPEED` as this PR does for `DESIRED_SPEED`.

**Comment by darcagn** [comment]
I know we discussed some of this on Discord, but I'm posting my replies on the PR for the record:

> As long as both dcload and dc-tool are both compiled with the same speed

I don't to recompile dcload and dc-tool with the same speed, I want to use all existing dcload-serial discs and the dcload-serial baked into my boot ROM, compiled with `SERIALSPEED` = 57600, to work with a dc-tool-ser binary that defaults to `1500000` baud rate without the use of the `-b` argument.

> Think about it this way: How does the behavior differ between setting INITIAL_SPEED to 115200 with this PR versus setting SERIALSPEED to the same without it? It doesn't have any effective difference.

It doesn't, but I didn't put `SERIALSPEED` in there, I'm simply leaving it in and renaming it for clarity, then adding in something new that represents what I want. Per our conversation in Discord I will remove it.

**Comment by darcagn** [comment]
Thanks! The requested changes have been made. You didn't comment on the `USER_BAUD_RATE` and `INIT_BAUD_RATE` names used within dc-tool but I adjusted them to `DEFAULT_SPEED` and `INITIAL_SPEED` to be more in line with the other changes and simplify things. Let me know if you object to anything in this change, but otherwise, it's behaving as I expect during tests, so I'm moving this out of draft.

**Review by ljsebald — APPROVED** [review]

**Pull request merged**
